グラフのボタン切替可能に変更
c-3lab/oasismap pull request #13
Opened 2024-02-06 01:53 UTC by hiromu-bit

2024-02-06 08:59 UTC, urabe0225 requested changes

2024-02-06 08:59 UTC, urabe0225 commented on frontend/src/app/happiness/all/page.tsx
> +  const [currentGraphIndex, setCurrentGraphIndex] = useState(2)
1行前の`period`を以下のように修正すれば、`currentGraphIndex`は不要です。
PeriodTypeが他で使用されていないか確認して、修正してください
```
export enum PeriodType {
  Month = 0,
  Day = 1,
  Time = 2,
}
```

2024-02-07 05:39 UTC, hiromu-bit commented on frontend/src/app/happiness/all/page.tsx
> +  const [currentGraphIndex, setCurrentGraphIndex] = useState(2)
161行目をexport enum PeriodType {
  Month = 0,
  Day = 1,
  Time = 2,
}
に変更することができなかった為、コンポーネント外で定義して修正しています。

2024-02-07 05:50 UTC, urabe0225 commented on frontend/src/app/happiness/all/page.tsx
> +  const [currentGraphIndex, setCurrentGraphIndex] = useState(2)
https://github.com/c-3lab/oasismap/blob/feature/mock/all-graph/frontend/src/types/period.ts
で定義されているPeriodTypeを直接修正してください

2024-02-07 05:58 UTC, hiromu-bit commented on frontend/src/app/happiness/all/page.tsx
> +  const [currentGraphIndex, setCurrentGraphIndex] = useState(2)
修正しました

2024-02-07 06:54 UTC, urabe0225 approved these changes

2024-02-07 06:55 UTC, merged