コードの整理
c-3lab/oasismap pull request #46
Opened 2024-02-28 03:12 UTC by hiromu-bit

2024-02-28 05:44 UTC, urabe0225 requested changes

2024-02-28 05:44 UTC, urabe0225 commented on frontend/src/components/map/mapset.tsx
> +                  <th>ワクワクする場所</th>
questionTitlesから取得するようにしてください

2024-02-28 05:52 UTC, hiromu-bit commented on frontend/src/components/map/mapset.tsx
> +                  <th>ワクワクする場所</th>
修正しました。

2024-03-04 06:03 UTC, urabe0225 approved these changes

2024-03-04 06:03 UTC, merged