グラフの背景・判例名称修正
c-3lab/oasismap pull request #47
Opened 2024-02-28 07:24 UTC by hiromu-bit

2024-02-28 08:17 UTC, urabe0225 requested changes

2024-02-28 08:17 UTC, urabe0225 commented on frontend/src/components/happiness/graph.tsx
> +            name="ワクワクする場所"
これも同じくquestionTitlesから取得するようにしてください

2024-02-28 08:17 UTC, urabe0225 commented on frontend/src/components/happiness/graph.tsx
> +            name="ワクワクする場所"
これも同じくquestionTitlesから取得するようにしてください

2024-02-29 04:24 UTC, urabe0225 approved these changes

2024-02-29 05:04 UTC, hiromu-bit commented on frontend/src/components/happiness/graph.tsx
> +            name="ワクワクする場所"
修正致しました

2024-02-29 05:04 UTC, hiromu-bit commented on frontend/src/components/happiness/graph.tsx
> +            name="ワクワクする場所"
修正致しました。

2024-02-29 07:09 UTC, merged