バックエンド プロジェクト作成
c-3lab/oasismap pull request #7
Opened 2024-01-25 07:27 UTC by i-kaneko-abel

2024-01-26 02:43 UTC, fwd-oki commented on backend/.husky/pre-commit
> +npx lint-staged
https://typicode.github.io/husky/how-to.html#project-not-in-git-root-directory

上記公式では以下のような記載となっているので修正をお願いします。
※frontend は backend に読み替えてください
※実行コマンド(npm test)は適宜修正してください
```
# frontend/.husky/pre-commit
cd frontend
npm test
```

2024-01-26 02:43 UTC, fwd-oki commented on backend/package.json
> +    "prepare": "cd .. && husky install backend/.husky",
https://typicode.github.io/husky/how-to.html#project-not-in-git-root-directory

上記公式では以下のような記載となっているので修正をお願いします。
`"prepare": "cd .. && husky frontend/.husky"`

2024-01-26 02:43 UTC, fwd-oki commented on backend/package.json
> +    "husky": "^5.2.0",
フロント側では `"husky": "^8.0.3",` となっているので合わせましょうか。

2024-01-26 02:55 UTC, fwd-oki commented on backend/package.json
> +  "license": "AGPL",
oasismap への適応は2箇所のみの修正なので別コミットといいかと思います。

- author 及び license をoasismap用に変更
- 接続ポートを oasismap用に変更

2024-01-26 02:55 UTC, fwd-oki commented on backend/src/main.ts
> +  await app.listen(4000);
前述の通り、こちらは別コミットでいいかと思います。

- 接続ポートを oasismap用に変更

2024-01-26 04:56 UTC, i-kaneko-abel commented on backend/package.json
> +    "prepare": "cd .. && husky install backend/.husky",
https://github.com/typicode/husky/releases?page=1
> v9 is backward compatible with v8, allowing you to freely upgrade and migrate your hooks later.
> package.json
> 
> ```
> {
>   "scripts": {
> -   "prepare": "husky install"
> +   "prepare": "husky"
>   }
> }
> ```

上記`install`を省略できるのはv9からのコマンドの様です。
v8系ではhusky **install**が必要の様でしたので、このままといたします。

2024-01-26 05:32 UTC, fwd-oki commented on docker-compose-dev.yml
> +      - ./site/mongo/configdb:/data/configdb
こちらはStartSeeker側からの流用かと思いますが、マウントは必要でしょうか？

2024-01-26 05:32 UTC, fwd-oki commented on docker-compose-dev.yml
> +      - ./operator/env:/work
こちらもStartSeeker側からの流用かと思いますが、マウントは必要でしょうか？
oasismap では基本的にOrionで登録されたデータ履歴管理の用途で使用するものとなる為、
不要だと思います。

2024-01-26 06:16 UTC, fwd-oki commented on README-dev.md
> +    xxxxx部分は編集したリポジトリに合わせて変更、初回のみ次回以降は不要。
> 初回のみ次回以降は不要。

別途指摘があった箇所かと思いますが日本語がおかしいので修正をお願いします。

2024-01-26 06:16 UTC, fwd-oki commented on README-dev.md
> +```
サブモジュールの読込は既に実施済ではないでしょうか？

2024-01-26 06:16 UTC, fwd-oki commented on README-dev.md
> +```
手順通りにいくと、ここでは `frontend/externals/StarSeeker` にいるので
```
cd ../../../
cp _env .env
```
とすべきかと思います。

2024-01-26 06:16 UTC, fwd-oki commented on README-dev.md
> +```
バックエンドの起動はコンテナ内ではなくホストマシンから起動するのでしょうか？
この後の手順でコンテナを起動していますが、バックエンドが重複してしまうかと思います。

2024-01-26 06:18 UTC, fwd-oki commented
プロジェクト作成のコミット a7f610b5d8633e03531058e0dd8be02923ea47a5 ですが、
コミットメッセージに少し違和感があるので以下に変更いただけますでしょうか。

nestプロジェクトインストール → nest new で初期プロジェクトを作成

2024-01-26 08:52 UTC, i-kaneko-abel commented on README-dev.md
> +```
> ## 以下 未マージのStarSeekerコードを利用したい場合
> 必要であれば以下手順を実行してください。

未マージのStarSeekerコードを利用しない場合、サブモジュールの読込を行っていないかと思うので記載しておりましたが、そもそも 未マージのStarSeekerコードを利用したい場合の手順を踏むと重複する為、少し構成を変更致しました。

2024-01-26 08:54 UTC, i-kaneko-abel commented on README-dev.md
> +```
未マージのStarSeekerコードを利用したい場合の手順を踏む場合そうですが、
通常通り行うとルートディレクトリにいるはずです。

2024-01-26 10:06 UTC, i-kaneko-abel commented on docker-compose-dev.yml
> +      - ./site/mongo/configdb:/data/configdb
必要である為、このままといたします。

2024-01-26 10:06 UTC, i-kaneko-abel commented on docker-compose-dev.yml
> +      - ./operator/env:/work
削除致しました。

2024-01-29 07:16 UTC, k-oizumi-abel commented on docker-compose-dev.yml
> +      npm run start:dev"
`npm run start:dev` は開発者が実行すると思いますので、手順に移動してこちらからは削除してください。

2024-01-29 07:21 UTC, k-oizumi-abel commented on README-dev.md
huskyの初期設定のためコマンドを追加するという話しが挙がっていたと思いますが、不要になったのでしょうか？
必要な場合はフロントエンド、バックエンドでそれぞれ実行する必要があると思います。

2024-01-29 07:21 UTC, k-oizumi-abel commented on README-dev.md
> +```
間に日本語を入れないのであればブロックを分ける必要はないと思いますので、
特に理由がなければ、1ブロックにまとめてしまって良いと思います。

2024-01-29 07:21 UTC, k-oizumi-abel commented on README-dev.md
> +curl若しくはpostman等でhttp://localhost:4000 に対してGETリクエスト送信。
手順が2つ以上あるので番号付き箇条書きにしたいです。

2024-01-29 07:21 UTC, k-oizumi-abel commented on README-dev.md
> +curl若しくはpostman等でhttp://localhost:4000 に対してGETリクエスト送信。
コマンド例は curl のみなので postman の記載はなくて良いと思います。

2024-01-29 07:21 UTC, k-oizumi-abel commented on README-dev.md
> +curl若しくはpostman等でhttp://localhost:4000 に対してGETリクエスト送信。
`http://localhost:4000` に送ることはコマンドを見ればわかるので、以下の curl コマンドでGETリクエストを送信する　などの方が適切だと思います。

2024-01-29 10:50 UTC, fwd-oki commented on README-dev.md
> +```
手順書の構成を見直したことで問題なくなった為、本指摘はクローズします。

2024-01-29 11:47 UTC, i-kaneko-abel commented on README-dev.md
`npm install`を実行すれば不要なハズです。

2024-01-29 13:38 UTC, Sheile commented on backend/.husky/.gitignore
`npm install`時（prepareでの`husky install`時）に自動的に作られるため、必ずしもコミットしておく必要は無いですね。
コミットしておくのもアリだとは思いますが、frontend側で未コミットだったため、差異があるのは気になります。

2024-01-29 13:41 UTC, Sheile commented on backend/.husky/pre-commit
> +npx lint-staged
`husky install`によるgit hookの導入は`.git/config`の`hookspath`で行われるため、frontend側の設定と競合してしまいます。
両対応できるスクリプトをルートの`.husky`に置くなど、何か対応が必要ですね。

```
# frontend側でのnpm install後
% git config --list | grep hook
core.hookspath=frontend/.husky

# backend側でのnpm install後
% git config --list | grep hook
core.hookspath=backend/.husky
```

2024-01-29 13:44 UTC, Sheile commented on backend/src/main.ts
> +  await app.listen(4000);
コンテナの環境変数`API_PORT`に従うべきかと思います。

2024-01-30 09:24 UTC, Sheile commented on docker-compose-dev.yml
> +        condition: service_healthy
frontend側で追加した時点で対応が漏れていたのですが、backendに[healthcheck定義](https://docs.docker.jp/compose/compose-file/compose-file-v3.html#healthcheck)が無いため起動に失敗しますね。

2024-01-30 10:02 UTC, Sheile commented on docker-compose.yml
>        npm run start"
コマンドの組み合わせが変ですね。

- `npm run start`: `dist`ディレクトリが無くても動作するので事前にbuildする必要は無い
- `npm run build`: `dist`ディレクトリが作成される

`dist`ディレクトリが必須な本番起動用スクリプトは `npm run start:prod`ですが、NestJSに詳しくないので`npm run start`とどちらを選ぶかまではわからないですね。
開発用(README-dev.md)は`npm run start:dev`で良いとして、本番用は以下のどちらかでしょうか。

1. `npm run start`のみ
2. `npm run build`して`npm run start:prod`

2024-01-31 09:40 UTC, k-oizumi-abel commented on backend/src/main.ts
> +  await app.listen(4000);
以下のように修正いたしました。
```ts
await app.listen(process.env.API_PORT ? process.env.API_PORT : 4000);
```

2024-01-31 09:42 UTC, k-oizumi-abel commented on docker-compose-dev.yml
> +        condition: service_healthy
`docker-compose-dev.yml` ではコンテナの中に入ってから開発者がプログラムを起動するため、コンテナ起動時はcurlが通らなくなってしまいました。
本ファイルから `depends_on` 自体を削除し、`docker-compose.yml` に `healthcheck` を追加しております。

2024-01-31 09:43 UTC, k-oizumi-abel commented on docker-compose.yml
>        npm run start"
`npm run build` を削除して `npm run start` のみにして問題なく動作することを確認いたしました。

2024-02-01 09:18 UTC, Sheile commented on backend/src/main.ts
> +  await app.listen(4000);
文字列型で良いのだろうかと思いましたが、`NestApplication#listen`が両対応しているんですね。
```
listen(port: string | number, ...args: any[]): Promise<any>
```
これであれば問題ないと思います。

2024-02-01 09:28 UTC, Sheile commented on docker-compose.yml
> -      - ./operator/env:/work
「バックエンド開発用docker環境を追加 」というコミットでPostgres用コンテナのマウントが変わっているのは少し変な気がしますが、意図したものでしょうか？

2024-02-01 09:29 UTC, Sheile commented on backend/.husky/.gitignore
追加してから消すぐらいであれば https://github.com/c-3lab/oasismap/pull/7/commits/77d4d1e6c4edff179498beaadc4e6ab6a34aaf4e の時点でコミットしない方が良いと思います。

2024-02-01 09:29 UTC, Sheile commented on .husky/pre-commit
追加してから書き換えるぐらいであれば https://github.com/c-3lab/oasismap/pull/7/commits/77d4d1e6c4edff179498beaadc4e6ab6a34aaf4e の時点でこの内容をコミットした方が良いと思います。

2024-02-01 09:30 UTC, Sheile commented on .husky/pre-commit
> +    echo "\e[31mError: Staged file '$FILE' is outside the '$TARGET' directory.\e[m"
ログレベルをWarningとErrorで使い分けた理由はありますか？

2024-02-01 09:32 UTC, Sheile commented on .husky/pre-commit
> +  if [ "$(echo $FILE | grep -E "^$TARGET/")" = "" ]; then
どちらもパスから先頭部分を確認したい処理ですが、TARGETの取り方と差異がありますね。
同じ処理に統一しておいた方が良いかと思います。

試していないですが、こんな感じでしょうか。
```
if [ "$(echo "$FILE" | cut -d "/" -f1)" != "$TARGET" ]; then
```

2024-02-01 09:35 UTC, Sheile commented on backend/package.json
> +    "prepare": "cd .. && husky install .husky",
`.husky`からインストールする場合は`.husky`引数は不要かもしれませんが、どうでしょう？

2024-02-01 11:10 UTC, k-oizumi-abel commented on .husky/pre-commit
> +# Prevent git commit in root directory
コメントは日本語で入れることになったと思うので、日本語で記載をお願いします。
また、メッセージについても日本語で良いと思います。

2024-02-02 01:42 UTC, i-kaneko-abel commented on docker-compose.yml
> -      - ./operator/env:/work
現状oasismapでは基本的にOrionで登録されたデータ履歴管理の用途で使用するので不要な認識かつ、
サブモジュールが移動となったので現状意図した動作をしなく、わざわざ修正する必要もないと思い削除致しましたが、念のため確認致します！

2024-02-02 01:56 UTC, Sheile commented on docker-compose.yml
> -      - ./operator/env:/work
削除自体の問題というわけではなく「バックエンド開発用docker環境を追加 」というコミットに入っているのは変という話ですね。

コミットを分けるか、コミットメッセージを変更でしょうか。
ちょっと他の修正とは毛色がことなるので前者を推奨。

2024-02-02 03:06 UTC, i-kaneko-abel commented on .husky/pre-commit
> +    echo "\e[31mError: Staged file '$FILE' is outside the '$TARGET' directory.\e[m"
Warning：階層を移動していない、Error：間違った階層にいるとの区別で分けておりましたが、
前者も間違った階層にいる点は同じかつErrorと言うのは大げさな気もするので、Warningで統一いたします。

2024-02-02 03:13 UTC, i-kaneko-abel commented on backend/.husky/.gitignore
@k-oizumi-abel さんと修正が重複する可能性があったので一旦別コミットにしておりました。
後ほど纏めます。

2024-02-02 03:13 UTC, i-kaneko-abel commented on .husky/pre-commit
@k-oizumi-abel さんと修正が重複する可能性があったので一旦別コミットにしておりました。
後ほど纏めます。

2024-02-02 09:30 UTC, Sheile commented on .husky/pre-commit
> +# Prevent git commit in root directory
>  また、メッセージについても日本語で良いと思います。

これが直っていないですね。

2024-02-05 10:25 UTC, urabe0225 requested changes

2024-02-05 10:25 UTC, urabe0225 commented on README-dev.md
> +cd backend
ディレクトリの位置関係としては`cd ../backend`が正しいです

2024-02-05 10:25 UTC, urabe0225 commented on README-dev.md
`docker compose -f docker-compose-dev.yml ps`の実行結果は以下であり、記載と異なります
```
NAME       IMAGE          COMMAND                  SERVICE    CREATED          STATUS          PORTS
backend    node:20.10.0   "docker-entrypoint.s…"   backend    33 seconds ago   Up 31 seconds   0.0.0.0:4000->4000/tcp, :::4000->4000/tcp
frontend   node:20.10.0   "docker-entrypoint.s…"   frontend   33 seconds ago   Up 31 seconds   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp
```

2024-02-06 01:08 UTC, i-kaneko-abel commented on README-dev.md
> +cd backend
修正致しました。

2024-02-06 01:08 UTC, i-kaneko-abel commented on README-dev.md
修正致しました。

2024-02-06 02:27 UTC, urabe0225 approved these changes

2024-02-19 06:04 UTC, k-oizumi-abel approved these changes

2024-02-19 15:58 UTC, Sheile approved these changes

2024-02-20 08:22 UTC, merged